import { defineReferences } from "@utils/references";

export default defineReferences({
  harris1988: {
    type: "inproceedings",
    authors: ["Chris Harris", "Mike Stephens"],
    title: "A combined corner and edge detector",
    proceedings: "Proceedings of the 4th Alvey Vision Conference",
    pages: "147-151",
    location: "Manchester, UK",
    year: 1988,
  },
  lowe1999: {
    type: "inproceedings",
    authors: "David G. Lowe",
    title: "Object recognition from local scale-invariant features",
    proceedings:
      "Proceedings of the 7th IEEE International Conference on Computer Vision (ICCV)",
    pages: "1150-1157",
    location: "Corfu, Greece",
    year: 1999,
    url: "https://www.cs.ubc.ca/~lowe/papers/iccv99.pdf",
  },
  lowe2004: {
    type: "article",
    authors: "David G. Lowe",
    title: "Distinctive image features from scale-invariant keypoints",
    journal: "International Journal of Computer Vision",
    volume: 60,
    issue: 2,
    pages: "91-110",
    year: 2004,
    url: "https://www.cs.ubc.ca/~lowe/papers/ijcv04.pdf",
  },
  rosin1999: {
    type: "article",
    authors: "Paul L. Rosin",
    title: "Measuring corner properties",
    journal: "Computer Vision and Image Understanding",
    volume: 73,
    issue: 2,
    pages: "291-307",
    year: 1999,
  },
  rosten2006: {
    type: "inproceedings",
    authors: ["Edward Rosten", "Tom Drummond"],
    title: "Machine learning for high-speed corner detection",
    proceedings: "European Conference on Computer Vision (ECCV)",
    pages: "430-443",
    publisher: "Springer",
    location: "Berlin, Heidelberg",
    year: 2006,
  },
  calonder2010: {
    type: "inproceedings",
    authors: ["Michael Calonder", "Vincent Lepetit", "Christoph Strecha", "Pascal Fua"],
    title: "BRIEF: Binary robust independent elementary features",
    proceedings: "European Conference on Computer Vision (ECCV)",
    pages: "778-792",
    publisher: "Springer",
    location: "Berlin, Heidelberg",
    year: 2010,
  },
  rublee2011: {
    type: "inproceedings",
    authors: ["Ethan Rublee", "Vincent Rabaud", "Kurt Konolige", "Gary Bradski"],
    title: "ORB: An efficient alternative to SIFT or SURF",
    proceedings:
      "Proceedings of the 2011 IEEE International Conference on Computer Vision (ICCV)",
    pages: "2564-2571",
    location: "Barcelona, Spain",
    year: 2011,
    doi: "10.1109/ICCV.2011.6126544",
  },
  griwodz2018: {
    type: "inproceedings",
    authors: ["Carsten Griwodz", "Lilian Calvet", "Pål Halvorsen"],
    title: "Popsift: A faithful SIFT implementation for real-time applications",
    proceedings: "Proceedings of the 9th ACM Multimedia Systems Conference (MMSys)",
    pages: "415-420",
    location: "Amsterdam, Netherlands",
    year: 2018,
  },
  bradski2000: {
    type: "article",
    authors: "Gary Bradski",
    title: "The OpenCV library",
    journal: "Dr. Dobb's Journal of Software Tools",
    year: 2000,
    note: "CUDA module documentation:",
    url: "https://docs.opencv.org/4.x/d6/d1d/group__cudafeatures2d.html",
  },
});
